changelog:
  exclude:
    labels:
      - duplicate
      - 'good first issue'
      - 'help wanted'
      - invalid
      - needs-tests
      - question
      - wontfix
      - skip-release-notes
  categories:
    - title: ⚡ Breaking
      labels:
        - breaking
    - title: 🚀 Improved
      labels:
        - enhancement
    - title: 🚑 Fixed
      labels:
        - bug
    - title: 👷 Changed
      labels:
        - maintenance
    - title: 📖 Documentation
      labels:
        - documentation
    - title: ⚙️ Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
