services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  mteu\Monitoring\:
    resource: '../Classes/*'

  # Import typed-extconf services
  mteu\TypedExtConf\Mapper\ConfigurationMapper:
    class: mteu\TypedExtConf\Mapper\ExtensionConfigurationMapper
    public: true
